import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import { CartProvider } from "@/context/CartContext";
import { OrderProvider } from "@/context/OrderContext";
import Navbar from "@/app/Header/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <AuthContextProvider>
          <CartProvider>
            <OrderProvider>
              <Navbar />
              <div className="flex justify-center px-4 pt-40">
                <div className="w-full max-w-7xl">
                  {children}
                </div>
              </div>
              <h1>this is footer</h1>
            </OrderProvider>
          </CartProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
